name: speech-BCI
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - comm=0.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - ipykernel=6.28.0
  - ipython=8.20.0
  - jedi=0.18.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=1.1.1w
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pip=24.0
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python=3.10.0
  - python-dateutil=2.9.0post0
  - pyzmq=25.1.2
  - readline=8.2
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tk=8.6.14
  - tornado=6.3.3
  - traitlets=5.7.1
  - tzdata=2024a
  - wcwidth=0.2.5
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==0.30.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alembic==1.13.1
      - antlr4-python3-runtime==4.9.3
      - async-timeout==4.0.3
      - attrs==23.2.0
      - autopage==0.5.2
      - bitsandbytes==0.43.1
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cliff==4.7.0
      - cloudpickle==3.0.0
      - cmaes==0.10.0
      - cmd2==2.4.3
      - colorlog==6.8.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - distance==0.1.3
      - docker-pycreds==0.4.0
      - edit-distance==1.0.6
      - filelock==3.14.0
      - fonttools==4.52.4
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - g2p-en==2.1.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - greenlet==3.0.3
      - grpcio==1.64.0
      - huggingface-hub==0.23.3
      - hydra-core==1.3.2
      - hydra-optuna-sweeper==1.2.0
      - hydra-submitit-launcher==1.1.5
      - idna==3.7
      - inflect==7.2.1
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - lightning==2.2.4
      - lightning-utilities==0.11.2
      - llvmlite==0.41.1
      - mako==1.3.5
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - more-itertools==10.2.0
      - multidict==6.0.5
      - nltk==3.8.1
      - numba==0.58.1
      - numpy==1.25.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - omegaconf==2.3.0
      - optuna==2.10.1
      - pbr==6.0.0
      - pillow==10.3.0
      - prettytable==3.10.0
      - protobuf==4.25.3
      - pyparsing==3.1.2
      - pyperclip==1.8.2
      - pytorch-lightning==2.2.4
      - pyyaml==6.0.1
      - regex==2024.5.15
      - requests==2.32.2
      - safetensors==0.4.3
      - scikit-learn==1.3.2
      - scipy==1.11.1
      - sentry-sdk==2.2.1
      - setproctitle==1.3.3
      - setuptools==70.0.0
      - smmap==5.0.1
      - sqlalchemy==2.0.30
      - stevedore==5.2.0
      - submitit==1.5.1
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - torch==1.13.1
      - torchmetrics==1.4.0.post0
      - tqdm==4.66.4
      - transformers==4.41.1
      - typeguard==4.2.1
      - typing-extensions==4.12.0rc1
      - urllib3==2.2.1
      - wandb==0.17.0
      - werkzeug==3.0.3
      - yarl==1.9.4
